WIP: Rollenbilder
ink-inc/MagicMittelalterStory pull request #67
Opened 2020-03-31 19:25 UTC by miafy

Überschriften & Stichpunkte eingefügt

2020-03-31 19:28 UTC, Medsmiley requested changes

2020-03-31 19:28 UTC, Medsmiley commented on Dokument/Dateien/Kultur.tex
> +	\item \textbf{Männer:}
ist noch ganz schön leer hier, sollte mehr geschrieben werden

2020-04-02 20:08 UTC, miafy commented
schließt #29

2020-04-02 20:12 UTC, Medsmiley requested changes

2020-04-02 20:12 UTC, Medsmiley commented on Dokument/Dateien/Kultur.tex
> +Außerdem folgen Sie meistens dem Try \& Error Prinzip.
sie klein

2020-04-02 20:12 UTC, Medsmiley commented on Dokument/Dateien/Kultur.tex
> +Außerdem ist Fingerfertigkeit meist eine Ihrer Stärken.
ihrer

2020-04-02 20:12 UTC, Medsmiley commented on Dokument/Dateien/Kultur.tex
> +Aufgrund ihrer Eigenschaften als Mutter wird Ihnen auch eher Empathie zugeschrieben.
ihnen

2020-04-02 20:12 UTC, Medsmiley commented on Dokument/Dateien/Kultur.tex
> +Das allgemeine Bild in der Gesellschaft ist die Gleichstellung beide Geschlechter.
beider

2020-04-02 20:12 UTC, Medsmiley commented on Dokument/Dateien/Kultur.tex
> +Will ein homosexuelles Pärchen eine Lebensgemeinschaft eingehen, dann verpflichten sie sich damit automatisch Kinder aufzunehmen, die von Ihrer eigentlichen Familie nicht mehr versorgt werden können
ihrer

2020-04-02 20:12 UTC, Medsmiley commented on Dokument/Dateien/Kultur.tex
> +
"Dem ist insbesondere so, weil die Armut in der Bevölkerung so stark ist und sie sehen müssen, wo sie bleiben. Verbunden hat sich das auch über die Religion mit der Ansicht, dass die Menschen die Gaben, die sie von den Göttern erhielten, zurückzahlen sollten, indem sie nach ihrem Ableben mit ihnen die bösen Götter bekämpfen."
oder so :D

2020-04-03 09:26 UTC, MineSchokokeks commented on Dokument/Dateien/Kultur.tex
> +Obwohl sie also keine Arbeit mehr leisten können, tragen sie positiv zur Gesellschaft bei.
Warum kann z.B. ein kampferprobter Heerführer in gehobenem Alter, der noch all seine Gliedmaßen besitzt, keine Arbeit mehr verrichten? Er ist vielleicht nicht mehr in seiner körperlichen Blüte, steht im Vergleich mit anderen doch aber immer noch gut da....

2020-04-03 09:27 UTC, MineSchokokeks approved these changes

2020-04-03 11:59 UTC, Medsmiley approved these changes

2020-04-03 11:59 UTC, merged