Aktualisierte Readmes
ink-inc/MagicMittelalterStory pull request #68
Opened 2020-04-01 12:38 UTC by Medsmiley

Ich habe die Readmes angepasst und eine neue geschaffen für unsere aktuellen Richtlinien. 
Anpassung: verbesserte Erklärung

2020-04-01 12:56 UTC, MineSchokokeks commented on README.md
> +Bitte halte dich daran. Sie sind zur schnellen Refrenz auch auf Discord festgehalten :)
*Referenz

2020-04-01 12:56 UTC, MineSchokokeks commented on README.md
> +Bitte halte dich daran. Sie sind zur schnellen Refrenz auch auf Discord festgehalten :)
*Referenz

2020-04-01 12:59 UTC, Medsmiley commented on README.md
> +Bitte halte dich daran. Sie sind zur schnellen Refrenz auch auf Discord festgehalten :)
erledigt

2020-04-01 12:59 UTC, Medsmiley commented on README.md
> +Bitte halte dich daran. Sie sind zur schnellen Refrenz auch auf Discord festgehalten :)
erledigt

2020-04-01 13:00 UTC, MineSchokokeks requested changes
Voll gut für Einsteiger. Manchmal bissel kompliziert erklärt, aber besser wäre es mir auch nicht eingefallen. Es ergibt eh alles sehr schnell Sinn, wenn man sich einmal eingearbeitet hat.
Bis auf die kleinen Rechtschreibfehler voll gut.
Anmerkung: Soll "master" eigentlich immer groß oder klein geschrieben sein?

2020-04-01 13:03 UTC, DDeckert commented on README_git_erklaerung.md
> +Änderungen, die am remote-Repository (aka online) gemacht wurden, werden nicht automatisch auch bei euch durchgeführt. Dafür müsst ihr erneut pullen.
"erneut pullen" klingt so, als müsste man das zweimal hintereinanderausführen

2020-04-01 13:07 UTC, DDeckert commented on README_git_setup.md
> +Nun ist die Anfrage eingegangen. Wenn mindstens 2 Leute sie sich angesehen und bestätigt (approved) haben, wird deine Änderung zum master hinzugefügt und offiziell.
mindestens

2020-04-01 13:21 UTC, Medsmiley commented
Ich hab Master später hauptsächlich klein geschrieben, weil der Branch auch so benannt ist...

2020-04-02 05:15 UTC, MineSchokokeks approved these changes

2020-04-02 20:04 UTC, miafy approved these changes

2020-04-02 20:05 UTC, merged