FÜGE HINZU: das Heer - Taktik, Struktur, Ausbildung und Image
ink-inc/MagicMittelalterStory pull request #87
Opened 2020-04-19 12:07 UTC by DDeckert

Das Heer wurde erzeugt (nimmte mehr Inspiration vom römischen Heer als den Bauernarmeen des Mittelalters ) und mit Taktiken und einer strukturierten Ausbildung versehen.

2020-04-21 12:07 UTC, Medsmiley requested changes

2020-04-21 12:07 UTC, Medsmiley commented on Handbuch/Dateien/Regierung.tex
> +In 5-Jahres-Zyklen gibt es eine Rotation der Streitkräfte: neue Rekruten werden in allen Teilen des Landes angeworben
Das war anders :)

2020-04-21 12:07 UTC, Medsmiley commented on Handbuch/Dateien/Regierung.tex
> +Nach dem ersten Jahr Ausbildung stehen die ersten Prüfungen an: Rekruten werden auf ihre Kampffähigkeit, Führungskraft und Loyalität getestet.
Führungskraft bei einfachen Soldaten?

2020-04-21 12:20 UTC, DDeckert commented on Handbuch/Dateien/Regierung.tex
> +Nach dem ersten Jahr Ausbildung stehen die ersten Prüfungen an: Rekruten werden auf ihre Kampffähigkeit, Führungskraft und Loyalität getestet.
Diejenigen, die gut darin sind, ihre Kameraden anzuführen, sind für mehr als eine normale Soldatenlaufbahn geeignet und werden für die Offizierslaufbahn empfohlen.

2020-05-12 17:58 UTC, Medsmiley approved these changes

2021-03-16 20:33 UTC, merged